### ISSUE TITLE
HTML format is broken

### ISSUE THREAD

**Issue by merkys** [tobyink/p5-spreadsheet-wright#7]
HTML format seems to be broken as of v0.107 (with `HTML::HTML5::Writer` v0.201, `XML::LibXML` v2.0128). To reproduce, one can change `xhtml` to `html` in test `04xhtml.t` from PR #6. The resulting HTML seems lacking most of closing XML marks:

```html
<!DOCTYPE html><title>Data</title><h1>Data</h1><table><caption>Discoveries</caption><tbody><tr><td>Name<td>Discovery<tr><td>Archimedes<td>Water displacement<tr><td>Albert Einstein<td>General relativity</table><table><caption>Names</caption><tbody><tr><td>Name<td>Surname<tr><td>Albert<td>Einstein<tr><td>Leonardo<td>Da Vinci</table>
```

**Comment by tobyink** [comment]
`</tr>`, `</td>`, and `</tbody>` are optional closing tags in both HTML 4 and HTML 5.

**Comment by tobyink** [comment]
https://dev.w3.org/html5/html-author/#the-tbody-element
https://dev.w3.org/html5/html-author/#the-tr-element
https://dev.w3.org/html5/html-author/#the-td-element

**Comment by merkys** [comment]
> `</tr>`, `</td>`, and `</tbody>` are optional closing tags in both HTML 4 and HTML 5.

This is new to me. Thanks for the explanation.
